### ISSUE TITLE
Client Patcher built from source code does absolutely nothing

### ISSUE THREAD

**Issue by uwuw7** [y9x/client-patcher#1]
Does nothing. I've tried everything and it does jack shit no matter what. Run as admin, rebuilt, used the patcher test instead of exe, nothing. :/ sucks cause the release with sploit only has one which works but would be nice to have both

**Comment by kaaax0815** [comment]
I saw no Loader or DLL Injector that actually injects into the Krunker Client. So I think he includes something malicious into the release

**Comment by e9x** [comment]
> I saw no Loader or DLL Injector that actually injects into the Krunker Client. So I think he includes something malicious into the release

This doesn't inject DLLs or load anything via the patcher. This patches clients, not injects.

**Comment by e9x** [comment]
> Does nothing. I've tried everything and it does jack shit no matter what. Run as admin, rebuilt, used the patcher test instead of exe, nothing. :/ sucks cause the release with sploit only has one which works but would be nice to have both

Apologies for the late reply. The latest source will load the Krunker Cheat Loader.
